name: CI

on: [push]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php: ['7.3', '7.4', '8.0']
        woo: ['latest']
    name: PHP ${{ matrix.php }} test for Woo ${{ matrix.woo }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          ini-values: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
          coverage: xdebug #optional, setup coverage driver

      - name: Composer install
        run: |
          composer config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          composer install

      - name: Install compatibility-with-php8-to-phpunit-7
        if: ${{ matrix.php == '8.0' }}
        run: |
          composer config --unset platform
          composer config repositories.0 '{"type":"vcs","url":"https://github.com/woocommerce/phpunit.git"}'
          composer require --dev --update-with-all-dependencies --ignore-platform-req=php phpunit/phpunit:dev-add-compatibility-with-php8-to-phpunit-7

      - name: Install WP Tests
        run: bash tests/bin/install.sh wordpress_test root root 127.0.0.1:${{ job.services.mysql.ports['3306'] }} latest ${{ matrix.woo }} true

      - name: phpunit tests
        run: ./vendor/bin/phpunit
